#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Path.ls": "00_core.ipynb",
         "PIL.Image.MAX_IMAGE_PIXELS": "00_core.ipynb",
         "image_extensions": "00_core.ipynb",
         "ImageSlicer": "00_core.ipynb",
         "PrintStatusCallback": "00_core.ipynb"}

modules = ["core.py"]

git_url = "https://github.com/fastai/Image.slicer/tree/master/"

def custom_doc_links(name): return None